/**
 * ImportController — turn outside material into knowledge notes.
 *
 * POST /api/import
 *   multipart/form-data: file (pdf | txt | md | audio) [+ title, category, tags]
 *   or JSON: { text, title?, category?, tags? }
 *
 * Pipeline: extract text (PDF parse / plain read / audio transcription) →
 * enqueue an AI "import" job that structures the material into a markdown
 * note. Flashcards and quiz questions are generated by the normal rebuild,
 * so an import automatically becomes study material.
 *
 * Returns 202 with the job id (same contract as POST /api/learn AI modes).
 */
import {
  Controller, Post, Body, UploadedFile, UseInterceptors, UseGuards,
  BadRequestException, HttpCode, Inject, NotImplementedException, BadGatewayException,
} from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { JobsService } from '../jobs/jobs.service';
import { ApiAuthGuard } from '../auth/auth.guard';
import { CurrentUser } from '../auth/current-user.decorator';
import { WritableGuard } from '../common/guards/writable.guard';
import { USAGE_SERVICE, UsageService } from '../usage/usage.interface';
import { TranscriptionService } from './transcription.service';

/** Extracted source text beyond this is truncated before prompting. */
const IMPORT_TEXT_CAP = 24_000;
const MAX_UPLOAD_BYTES = 30 * 1024 * 1024;

const AUDIO_MIMES = new Set([
  'audio/mpeg', 'audio/mp4', 'audio/x-m4a', 'audio/m4a', 'audio/wav', 'audio/x-wav',
  'audio/webm', 'audio/ogg', 'audio/flac', 'video/webm', 'video/mp4',
]);
const TEXT_MIMES = new Set(['text/plain', 'text/markdown', 'application/octet-stream']);

@Controller('api/import')
@UseGuards(ApiAuthGuard)
export class ImportController {
  constructor(
    private readonly jobsService: JobsService,
    private readonly transcription: TranscriptionService,
    @Inject(USAGE_SERVICE) private readonly usage: UsageService,
  ) {}

  @Post()
  @HttpCode(202)
  @UseGuards(WritableGuard)
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: MAX_UPLOAD_BYTES } }))
  async importSource(
    @CurrentUser() userId: string,
    @UploadedFile() file: { originalname: string; buffer: Buffer; mimetype: string } | undefined,
    @Body() body: any,
  ) {
    const title = typeof body?.title === 'string' ? body.title.trim() : '';
    const category = typeof body?.category === 'string' ? body.category.trim() : '';
    const tags = this.parseTags(body?.tags);

    let text = '';
    let sourceName = '';
    let sourceKind: 'text' | 'pdf' | 'audio' = 'text';

    if (file) {
      sourceName = file.originalname || 'upload';
      const ext = (sourceName.match(/\.([A-Za-z0-9]+)$/)?.[1] || '').toLowerCase();
      if (file.mimetype === 'application/pdf' || ext === 'pdf') {
        sourceKind = 'pdf';
        text = await this.extractPdf(file.buffer);
      } else if (AUDIO_MIMES.has(file.mimetype) || ['mp3', 'm4a', 'wav', 'webm', 'ogg', 'flac', 'mp4'].includes(ext)) {
        sourceKind = 'audio';
        if (!this.transcription.enabled) {
          throw new NotImplementedException('audio transcription is not configured (set TRANSCRIBE_API_KEY or TRANSCRIBE_COMMAND)');
        }
        text = await this.transcription.transcribe(file).catch((err) => {
          if (err?.status === 501) throw new NotImplementedException(err.message);
          throw new BadGatewayException(err?.message || 'transcription failed');
        });
      } else if (TEXT_MIMES.has(file.mimetype) || ['txt', 'md', 'markdown'].includes(ext)) {
        text = file.buffer.toString('utf8');
      } else {
        throw new BadRequestException(`unsupported file type: ${file.mimetype || ext || 'unknown'}`);
      }
    } else if (typeof body?.text === 'string' && body.text.trim()) {
      text = body.text;
      sourceName = title || 'pasted text';
    } else {
      throw new BadRequestException('provide a file upload or a "text" field');
    }

    text = text.replace(/\u0000/g, '').trim();
    if (text.length < 40) {
      throw new BadRequestException('could not extract enough text from the source (got fewer than 40 characters)');
    }
    const truncated = text.length > IMPORT_TEXT_CAP;
    if (truncated) text = text.slice(0, IMPORT_TEXT_CAP);

    // Imports consume the shared AI quota pool, like research capture.
    await this.usage.checkQuota(userId, 'codex.research');
    await this.usage.track(userId, 'codex.research', { mode: 'import', kind: sourceKind });

    const job = await this.jobsService.enqueue(userId, {
      mode: 'import',
      topic: title || sourceName,
      title: title || sourceName,
      body: text,
      category,
      tags,
      sourceName,
      sourceKind,
      sourceTruncated: truncated,
    });
    return { jobId: job.id, job, extractedChars: text.length, truncated };
  }

  private parseTags(value: unknown): string[] {
    if (Array.isArray(value)) return value.map((t) => String(t).trim()).filter(Boolean).slice(0, 15);
    if (typeof value === 'string') return value.split(',').map((t) => t.trim()).filter(Boolean).slice(0, 15);
    return [];
  }

  private async extractPdf(buffer: Buffer): Promise<string> {
    try {
      // Deep path avoids pdf-parse's index.js debug harness (it tries to read
      // a test PDF from disk when loaded outside a parent module).
      const { default: pdfParse } = await import('pdf-parse/lib/pdf-parse.js' as string);
      const parsed = await pdfParse(buffer);
      return String(parsed.text || '');
    } catch (err) {
      throw new BadRequestException(`could not parse PDF: ${(err as Error).message}`);
    }
  }
}
