/**
 * Database migration runner for SQLite and PostgreSQL.
 *
 * Why not drizzle-kit migrate?
 *   drizzle-kit migrate requires migration files generated by drizzle-kit generate,
 *   which compares the schema to the PREVIOUS migration files — not to the live DB.
 *   For a local-first app shipped as a self-contained binary with no migration CLI step,
 *   running migrations at startup from code is more reliable.
 *
 * Strategy:
 *   - A `__migrations` table tracks applied migration IDs.
 *   - Each migration is a TypeScript function so logic (PRAGMA, IF NOT EXISTS,
 *     table rebuilds) can be expressed clearly rather than fragile raw SQL.
 *   - Migrations are idempotent: they check before acting. Re-running the server
 *     on an already-migrated database is always safe.
 *   - SQLite migrations run synchronously (better-sqlite3 API).
 *   - PostgreSQL migrations run asynchronously (node-postgres API).
 *
 * Adding a new migration:
 *   1. Add a new entry to SQLITE_MIGRATIONS (and PG_MIGRATIONS if PG is used).
 *   2. Increment the id counter.
 *   3. Implement the `run` / `runAsync` function — check before altering.
 *   Never edit or re-order existing migrations.
 */

import { Logger } from '@nestjs/common';
import { cpSync, existsSync, mkdirSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import type Database from 'better-sqlite3';
import type { Pool } from 'pg';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Returns the set of column names for a table in SQLite. */
function sqliteColumns(db: Database.Database, table: string): Set<string> {
  const rows = db.prepare(`PRAGMA table_info(${table})`).all() as { name: string }[];
  return new Set(rows.map((r) => r.name));
}

/** Returns the set of column names for a table in PostgreSQL. */
async function pgColumns(pool: Pool, table: string): Promise<Set<string>> {
  const { rows } = await pool.query(
    `SELECT column_name FROM information_schema.columns WHERE table_name = $1`,
    [table],
  );
  return new Set(rows.map((r: any) => r.column_name));
}

function addIfMissing(db: Database.Database, table: string, column: string, definition: string): void {
  if (!sqliteColumns(db, table).has(column)) {
    db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
  }
}

async function pgAddIfMissing(pool: Pool, table: string, column: string, definition: string): Promise<void> {
  const cols = await pgColumns(pool, table);
  if (!cols.has(column)) {
    await pool.query(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
  }
}

// ---------------------------------------------------------------------------
// SQLite migrations
// ---------------------------------------------------------------------------

const SQLITE_CREATE_MIGRATIONS_TABLE = `
  CREATE TABLE IF NOT EXISTS __migrations (
    id         TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL
  )
`;

interface SqliteMigration {
  id: string;
  run(db: Database.Database): void;
}

const SQLITE_MIGRATIONS: SqliteMigration[] = [
  {
    id: '0000_initial_schema',
    run(db) {
      db.exec(`
        PRAGMA journal_mode = WAL;
        PRAGMA foreign_keys = ON;

        CREATE TABLE IF NOT EXISTS jobs (
          id          TEXT    PRIMARY KEY,
          status      TEXT    NOT NULL,
          mode        TEXT    NOT NULL,
          topic       TEXT    NOT NULL,
          attempts    INTEGER NOT NULL DEFAULT 0,
          maxAttempts INTEGER NOT NULL DEFAULT 0,
          createdAt   TEXT    NOT NULL,
          startedAt   TEXT,
          finishedAt  TEXT,
          nextRunAt   TEXT,
          error       TEXT,
          payload     TEXT    NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_jobs_status_next_run ON jobs(status, nextRunAt);
        CREATE INDEX IF NOT EXISTS idx_jobs_created_at      ON jobs(createdAt);

        CREATE TABLE IF NOT EXISTS reminders (
          id          TEXT PRIMARY KEY,
          noteId      TEXT NOT NULL,
          remindAt    TEXT NOT NULL,
          message     TEXT NOT NULL DEFAULT '',
          createdAt   TEXT NOT NULL,
          completedAt TEXT
        );
        CREATE INDEX IF NOT EXISTS idx_reminders_note_id      ON reminders(noteId);
        CREATE INDEX IF NOT EXISTS idx_reminders_remind_at    ON reminders(remindAt);
        CREATE INDEX IF NOT EXISTS idx_reminders_completed_at ON reminders(completedAt);

        CREATE TABLE IF NOT EXISTS flashcard_cache (
          noteId      TEXT PRIMARY KEY,
          hash        TEXT NOT NULL,
          cards       TEXT NOT NULL,
          generatedAt TEXT NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_flashcard_cache_hash ON flashcard_cache(hash);

        CREATE TABLE IF NOT EXISTS flashcard_reviews (
          cardId      TEXT PRIMARY KEY,
          noteId      TEXT NOT NULL,
          isUserCard  INTEGER NOT NULL DEFAULT 0,
          easeFactor  TEXT NOT NULL DEFAULT '2.5',
          interval    INTEGER NOT NULL DEFAULT 0,
          repetitions INTEGER NOT NULL DEFAULT 0,
          nextReviewAt TEXT,
          lastReviewAt TEXT,
          lastRating  TEXT
        );
        CREATE INDEX IF NOT EXISTS idx_flashcard_reviews_note_id     ON flashcard_reviews(noteId);
        CREATE INDEX IF NOT EXISTS idx_flashcard_reviews_next_review  ON flashcard_reviews(nextReviewAt);

        CREATE TABLE IF NOT EXISTS user_flashcards (
          id          TEXT PRIMARY KEY,
          noteId      TEXT NOT NULL,
          prompt      TEXT NOT NULL,
          lesson      TEXT NOT NULL,
          kind        TEXT NOT NULL DEFAULT 'concept',
          createdAt   TEXT NOT NULL,
          updatedAt   TEXT NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_user_flashcards_note_id ON user_flashcards(noteId);

        CREATE TABLE IF NOT EXISTS hidden_flashcards (
          cardId    TEXT PRIMARY KEY,
          createdAt TEXT NOT NULL
        );
      `);
    },
  },

  {
    id: '0001_add_userid_columns',
    run(db) {
      // Simple ADD COLUMN for tables where the primary key stays the same.
      const simpleAlters: [string, string][] = [
        ['jobs',              'userId TEXT NOT NULL DEFAULT ""'],
        ['reminders',         'userId TEXT NOT NULL DEFAULT ""'],
        ['flashcard_reviews', 'userId TEXT NOT NULL DEFAULT ""'],
        ['user_flashcards',   'userId TEXT NOT NULL DEFAULT ""'],
        ['hidden_flashcards', 'userId TEXT NOT NULL DEFAULT ""'],
      ];
      for (const [table, def] of simpleAlters) {
        addIfMissing(db, table, 'userId', def);
      }

      // flashcard_cache needs a table rebuild because the primary key changes
      // from (noteId) → (userId, noteId). SQLite cannot ALTER a PRIMARY KEY.
      const cacheHasUserId = sqliteColumns(db, 'flashcard_cache').has('userId');
      if (!cacheHasUserId) {
        db.exec(`
          CREATE TABLE flashcard_cache_new (
            userId      TEXT NOT NULL DEFAULT '',
            noteId      TEXT NOT NULL,
            hash        TEXT NOT NULL,
            cards       TEXT NOT NULL,
            generatedAt TEXT NOT NULL,
            PRIMARY KEY (userId, noteId)
          );
          INSERT INTO flashcard_cache_new (userId, noteId, hash, cards, generatedAt)
            SELECT '', noteId, hash, cards, generatedAt FROM flashcard_cache;
          DROP TABLE flashcard_cache;
          ALTER TABLE flashcard_cache_new RENAME TO flashcard_cache;
          CREATE INDEX IF NOT EXISTS idx_flashcard_cache_user_id ON flashcard_cache(userId);
        `);
      }

      // Add remaining indexes now that userId columns exist.
      db.exec(`
        CREATE INDEX IF NOT EXISTS idx_jobs_user_id             ON jobs(userId);
        CREATE INDEX IF NOT EXISTS idx_reminders_user_id        ON reminders(userId);
        CREATE INDEX IF NOT EXISTS idx_flashcard_reviews_user_id ON flashcard_reviews(userId);
        CREATE INDEX IF NOT EXISTS idx_user_flashcards_user_id  ON user_flashcards(userId);
        CREATE INDEX IF NOT EXISTS idx_hidden_flashcards_user_id ON hidden_flashcards(userId);
      `);
    },
  },
  {
    id: '0002_assign_local_userid',
    run(db) {
      // Reassign all rows created before auth existed (userId='') to userId='local'.
      // These are pre-auth records from single-user local installs.
      const TABLES = [
        'jobs', 'reminders', 'flashcard_cache',
        'flashcard_reviews', 'user_flashcards', 'hidden_flashcards',
      ];
      for (const table of TABLES) {
        db.prepare(`UPDATE ${table} SET userId = 'local' WHERE userId = ''`).run();
      }
    },
  },
  {
    id: '0003_quiz_tables',
    run(db) {
      db.exec(`
        CREATE TABLE IF NOT EXISTS quiz_cache (
          userId      TEXT NOT NULL DEFAULT '',
          noteId      TEXT NOT NULL,
          hash        TEXT NOT NULL,
          questions   TEXT NOT NULL,
          generatedAt TEXT NOT NULL,
          PRIMARY KEY (userId, noteId)
        );
        CREATE INDEX IF NOT EXISTS idx_quiz_cache_user_id ON quiz_cache(userId);

        CREATE TABLE IF NOT EXISTS quiz_reviews (
          questionId   TEXT PRIMARY KEY,
          userId       TEXT NOT NULL DEFAULT '',
          noteId       TEXT NOT NULL,
          nextReviewAt TEXT,
          lastReviewAt TEXT,
          lastRating   TEXT,
          streak       INTEGER NOT NULL DEFAULT 0
        );
        CREATE INDEX IF NOT EXISTS idx_quiz_reviews_user_id   ON quiz_reviews(userId);
        CREATE INDEX IF NOT EXISTS idx_quiz_reviews_note_id   ON quiz_reviews(noteId);
        CREATE INDEX IF NOT EXISTS idx_quiz_reviews_next      ON quiz_reviews(nextReviewAt);

        CREATE TABLE IF NOT EXISTS quiz_hidden (
          questionId TEXT PRIMARY KEY,
          userId     TEXT NOT NULL DEFAULT '',
          createdAt  TEXT NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_quiz_hidden_user_id ON quiz_hidden(userId);
      `);
    },
  },
  {
    id: '0004_note_reads',
    run(db) {
      db.exec(`
        CREATE TABLE IF NOT EXISTS note_reads (
          userId      TEXT NOT NULL DEFAULT '',
          noteId      TEXT NOT NULL,
          readCount   INTEGER NOT NULL DEFAULT 1,
          firstReadAt TEXT NOT NULL,
          lastReadAt  TEXT NOT NULL,
          PRIMARY KEY (userId, noteId)
        );
        CREATE INDEX IF NOT EXISTS idx_note_reads_user_id ON note_reads(userId);
        CREATE INDEX IF NOT EXISTS idx_note_reads_note_id ON note_reads(noteId);
      `);
    },
  },
  {
    id: '0005_user_settings',
    run(db) {
      db.exec(`
        CREATE TABLE IF NOT EXISTS user_settings (
          userId   TEXT NOT NULL PRIMARY KEY,
          settings TEXT NOT NULL DEFAULT '{}'
        );
      `);
    },
  },
];

// ---------------------------------------------------------------------------
// Helpers used by migrations only during server startup
// ---------------------------------------------------------------------------

/** Count all files under a directory recursively. */
function countFilesRecursive(dir: string): number {
  if (!existsSync(dir)) return 0;
  let n = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    n += entry.isDirectory() ? countFilesRecursive(join(dir, entry.name)) : 1;
  }
  return n;
}

/**
 * Copy legacy single-user notes into the per-user path for 'local'.
 * Called by the server's DatabaseModule after migrations run.
 * Non-destructive: never overwrites files that already exist in the destination.
 */
export function migrateLocalNoteFiles(knowledgeDir: string, logger: Logger): void {
  const src = join(knowledgeDir, 'notes');
  const dst = join(knowledgeDir, 'users', 'local', 'notes');

  if (!existsSync(src)) return;

  const srcCount = countFilesRecursive(src);
  if (srcCount === 0) return;

  const dstCount = countFilesRecursive(dst);
  if (dstCount >= srcCount) return; // already migrated

  mkdirSync(dst, { recursive: true });
  cpSync(src, dst, { recursive: true, force: false, errorOnExist: false });
  logger.log(`Migrated ${srcCount} legacy note file(s) → users/local/notes/`);
}

export function runSqliteMigrations(db: Database.Database, logger: Logger): void {
  db.exec(SQLITE_CREATE_MIGRATIONS_TABLE);

  const applied = new Set(
    (db.prepare('SELECT id FROM __migrations').all() as { id: string }[]).map((r) => r.id),
  );

  for (const migration of SQLITE_MIGRATIONS) {
    if (applied.has(migration.id)) continue;

    db.transaction(() => {
      migration.run(db);
      db.prepare('INSERT INTO __migrations (id, applied_at) VALUES (?, ?)').run(
        migration.id,
        new Date().toISOString(),
      );
    })();

    logger.log(`Applied SQLite migration: ${migration.id}`);
  }
}

// ---------------------------------------------------------------------------
// PostgreSQL migrations
// ---------------------------------------------------------------------------

interface PgMigration {
  id: string;
  run(pool: Pool): Promise<void>;
}

const PG_MIGRATIONS: PgMigration[] = [
  {
    id: '0000_initial_schema',
    async run(pool) {
      await pool.query(`
        CREATE TABLE IF NOT EXISTS jobs (
          id           TEXT    PRIMARY KEY,
          status       TEXT    NOT NULL,
          mode         TEXT    NOT NULL,
          topic        TEXT    NOT NULL,
          attempts     INTEGER NOT NULL DEFAULT 0,
          "maxAttempts" INTEGER NOT NULL DEFAULT 0,
          "createdAt"  TEXT    NOT NULL,
          "startedAt"  TEXT,
          "finishedAt" TEXT,
          "nextRunAt"  TEXT,
          error        TEXT,
          payload      TEXT    NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_jobs_status_next_run ON jobs(status, "nextRunAt");
        CREATE INDEX IF NOT EXISTS idx_jobs_created_at      ON jobs("createdAt");

        CREATE TABLE IF NOT EXISTS reminders (
          id           TEXT PRIMARY KEY,
          "noteId"     TEXT NOT NULL,
          "remindAt"   TEXT NOT NULL,
          message      TEXT NOT NULL DEFAULT '',
          "createdAt"  TEXT NOT NULL,
          "completedAt" TEXT
        );
        CREATE INDEX IF NOT EXISTS idx_reminders_note_id      ON reminders("noteId");
        CREATE INDEX IF NOT EXISTS idx_reminders_remind_at    ON reminders("remindAt");
        CREATE INDEX IF NOT EXISTS idx_reminders_completed_at ON reminders("completedAt");

        CREATE TABLE IF NOT EXISTS flashcard_cache (
          "userId"      TEXT NOT NULL DEFAULT '',
          "noteId"      TEXT NOT NULL,
          hash          TEXT NOT NULL,
          cards         TEXT NOT NULL,
          "generatedAt" TEXT NOT NULL,
          PRIMARY KEY ("userId", "noteId")
        );
        CREATE INDEX IF NOT EXISTS idx_flashcard_cache_user_id ON flashcard_cache("userId");
        CREATE INDEX IF NOT EXISTS idx_flashcard_cache_hash    ON flashcard_cache(hash);

        CREATE TABLE IF NOT EXISTS flashcard_reviews (
          "cardId"      TEXT PRIMARY KEY,
          "noteId"      TEXT NOT NULL,
          "isUserCard"  INTEGER NOT NULL DEFAULT 0,
          "easeFactor"  TEXT NOT NULL DEFAULT '2.5',
          "interval"    INTEGER NOT NULL DEFAULT 0,
          "repetitions" INTEGER NOT NULL DEFAULT 0,
          "nextReviewAt" TEXT,
          "lastReviewAt" TEXT,
          "lastRating"  TEXT
        );
        CREATE INDEX IF NOT EXISTS idx_flashcard_reviews_note_id    ON flashcard_reviews("noteId");
        CREATE INDEX IF NOT EXISTS idx_flashcard_reviews_next_review ON flashcard_reviews("nextReviewAt");

        CREATE TABLE IF NOT EXISTS user_flashcards (
          id           TEXT PRIMARY KEY,
          "noteId"     TEXT NOT NULL,
          prompt       TEXT NOT NULL,
          lesson       TEXT NOT NULL,
          kind         TEXT NOT NULL DEFAULT 'concept',
          "createdAt"  TEXT NOT NULL,
          "updatedAt"  TEXT NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_user_flashcards_note_id ON user_flashcards("noteId");

        CREATE TABLE IF NOT EXISTS hidden_flashcards (
          "cardId"     TEXT PRIMARY KEY,
          "createdAt"  TEXT NOT NULL
        );
      `);
    },
  },
  {
    id: '0001_add_userid_columns',
    async run(pool) {
      const tables: [string, string, string][] = [
        ['jobs',              'userId', 'TEXT NOT NULL DEFAULT \'\''],
        ['reminders',         'userId', 'TEXT NOT NULL DEFAULT \'\''],
        ['flashcard_reviews', 'userId', 'TEXT NOT NULL DEFAULT \'\''],
        ['user_flashcards',   'userId', 'TEXT NOT NULL DEFAULT \'\''],
        ['hidden_flashcards', 'userId', 'TEXT NOT NULL DEFAULT \'\''],
      ];
      for (const [table, col, def] of tables) {
        await pgAddIfMissing(pool, table, col, def);
      }
      // flashcard_cache already has userId in 0000 for PG (fresh install).
      // For existing PG DBs that were created without userId, recreate the table.
      const cacheHasUserId = await pgColumns(pool, 'flashcard_cache');
      if (!cacheHasUserId.has('userId')) {
        await pool.query(`
          CREATE TABLE flashcard_cache_new (
            "userId"      TEXT NOT NULL DEFAULT '',
            "noteId"      TEXT NOT NULL,
            hash          TEXT NOT NULL,
            cards         TEXT NOT NULL,
            "generatedAt" TEXT NOT NULL,
            PRIMARY KEY ("userId", "noteId")
          );
          INSERT INTO flashcard_cache_new ("userId", "noteId", hash, cards, "generatedAt")
            SELECT '', "noteId", hash, cards, "generatedAt" FROM flashcard_cache;
          DROP TABLE flashcard_cache;
          ALTER TABLE flashcard_cache_new RENAME TO flashcard_cache;
        `);
      }
      await pool.query(`
        CREATE INDEX IF NOT EXISTS idx_jobs_user_id              ON jobs("userId");
        CREATE INDEX IF NOT EXISTS idx_reminders_user_id         ON reminders("userId");
        CREATE INDEX IF NOT EXISTS idx_flashcard_reviews_user_id ON flashcard_reviews("userId");
        CREATE INDEX IF NOT EXISTS idx_user_flashcards_user_id   ON user_flashcards("userId");
        CREATE INDEX IF NOT EXISTS idx_hidden_flashcards_user_id ON hidden_flashcards("userId");
      `);
    },
  },
  {
    id: '0002_assign_local_userid_pg',
    async run(pool) {
      const TABLES = ['jobs', 'reminders', 'flashcard_cache', 'flashcard_reviews', 'user_flashcards', 'hidden_flashcards'];
      for (const table of TABLES) {
        await pool.query(`UPDATE ${table} SET "userId" = 'local' WHERE "userId" = ''`);
      }
    },
  },
  {
    id: '0003_quiz_tables_pg',
    async run(pool) {
      await pool.query(`
        CREATE TABLE IF NOT EXISTS quiz_cache (
          "userId"      TEXT NOT NULL DEFAULT '',
          "noteId"      TEXT NOT NULL,
          hash          TEXT NOT NULL,
          questions     TEXT NOT NULL,
          "generatedAt" TEXT NOT NULL,
          PRIMARY KEY ("userId", "noteId")
        );
        CREATE INDEX IF NOT EXISTS idx_quiz_cache_user_id ON quiz_cache("userId");

        CREATE TABLE IF NOT EXISTS quiz_reviews (
          "questionId"   TEXT PRIMARY KEY,
          "userId"       TEXT NOT NULL DEFAULT '',
          "noteId"       TEXT NOT NULL,
          "nextReviewAt" TEXT,
          "lastReviewAt" TEXT,
          "lastRating"   TEXT,
          streak         INTEGER NOT NULL DEFAULT 0
        );
        CREATE INDEX IF NOT EXISTS idx_quiz_reviews_user_id ON quiz_reviews("userId");
        CREATE INDEX IF NOT EXISTS idx_quiz_reviews_note_id ON quiz_reviews("noteId");
        CREATE INDEX IF NOT EXISTS idx_quiz_reviews_next    ON quiz_reviews("nextReviewAt");

        CREATE TABLE IF NOT EXISTS quiz_hidden (
          "questionId" TEXT PRIMARY KEY,
          "userId"     TEXT NOT NULL DEFAULT '',
          "createdAt"  TEXT NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_quiz_hidden_user_id ON quiz_hidden("userId");
      `);
    },
  },
];

export async function runPgMigrations(pool: Pool, logger: Logger): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS __migrations (
      id         TEXT PRIMARY KEY,
      applied_at TEXT NOT NULL
    )
  `);

  const { rows } = await pool.query('SELECT id FROM __migrations');
  const applied = new Set(rows.map((r: any) => r.id));

  for (const migration of PG_MIGRATIONS) {
    if (applied.has(migration.id)) continue;

    await pool.query('BEGIN');
    try {
      await migration.run(pool);
      await pool.query(
        'INSERT INTO __migrations (id, applied_at) VALUES ($1, $2)',
        [migration.id, new Date().toISOString()],
      );
      await pool.query('COMMIT');
    } catch (err) {
      await pool.query('ROLLBACK');
      throw err;
    }

    logger.log(`Applied PostgreSQL migration: ${migration.id}`);
  }
}
